In [1]:
%pylab inline

import pandas as pd
import seaborn as sns
sns.set()
import pickle
from sklearn.model_selection import train_test_split , cross_val_score, StratifiedShuffleSplit
from sklearn.preprocessing import StandardScaler, PolynomialFeatures, OneHotEncoder
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier

Populating the interactive namespace from numpy and matplotlib


In [2]:
with open('atxac_de.pickle', 'rb') as read_aacde:
    atxac_df = pickle.load(read_aacde)

In [3]:
X = atxac_df.drop(columns=['Outcome_Type','Updated_Outcome_Type'])
y = atxac_df['Updated_Outcome_Type']

In [4]:
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=.2, random_state=88,stratify=y)

In [5]:
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=.25, random_state=24,stratify=y_train_val)

In [7]:
ohe = OneHotEncoder(handle_unknown='ignore')
ohe.fit(X_train[['Sex_Upon_Outcome','Intake_Type','Intake_Condition']])
top3 = ohe.transform(X_train[['Sex_Upon_Outcome','Intake_Type','Intake_Condition']]).toarray()

In [8]:
tree = DecisionTreeClassifier()
tree.fit(top3, y_train)

DecisionTreeClassifier()

In [9]:
top3_val = ohe.transform(X_val[['Sex_Upon_Outcome','Intake_Type','Intake_Condition']]).toarray()

In [10]:
y_pred = tree.predict(top3_val)

In [12]:
tree.score(y_val,y_pred)

ValueError: could not convert string to float: 'Adoption'

In [11]:
print("RF confusion matrix: \n\n", metrics.confusion_matrix(y_val, y_pred,labels=['Adoption','Transfer','Other']))

RF confusion matrix: 

 [[4550  263   60]
 [1184 2900  157]
 [ 520  331  292]]


In [15]:
features = ['Sex_Upon_Outcome','Intake_Type','Intake_Condition','OutcomeBreed' , 'OutcomeColor']
ohe = OneHotEncoder(handle_unknown='ignore')
ohe.fit(X_train[features])
all5 = ohe.transform(X_train[features]).toarray()
all5_val = ohe.transform(X_val[features]).toarray()

In [16]:
tree = DecisionTreeClassifier()
tree.fit(all5, y_train)

DecisionTreeClassifier()

In [17]:
y_pred = tree.predict(all5_val)

In [18]:
print("RF confusion matrix: \n\n", metrics.confusion_matrix(y_val, y_pred,labels=['Adoption','Transfer','Other']))

RF confusion matrix: 

 [[4483  303   87]
 [1180 2874  187]
 [ 514  340  289]]
