In [2]:
%pylab inline

import pandas as pd
import seaborn as sns
sns.set()
import pickle

from sklearn.model_selection import train_test_split , cross_val_score, StratifiedShuffleSplit 
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, PolynomialFeatures, OneHotEncoder
from sklearn import metrics

Populating the interactive namespace from numpy and matplotlib


In [3]:
with open('atxac_de.pickle', 'rb') as read_aacde:
    atxac_df = pickle.load(read_aacde)

In [4]:
X = atxac_df.drop(columns=['Outcome_Type','Updated_Outcome_Type'])
y = atxac_df['Updated_Outcome_Type']

In [5]:
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=.2, random_state=88,stratify=y)

In [6]:
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=.25, random_state=24,stratify=y_train_val)

In [ ]:
sns.pairplot(df_train, corner=True, height=1.5, plot_kws={'size': 3}, hue='in_sf');

In [52]:
lm_ovr = LogisticRegression(multi_class='ovr',max_iter=10000)
lm_mn = LogisticRegression(multi_class='multinomial',max_iter=10000)

In [24]:
lm_ovr.fit(X_train, y_train)
lm_mn.fit(X_train, y_train)

ValueError: could not convert string to float: 'A685151'

In [53]:
features = ['Sex_Upon_Outcome','Intake_Type','Intake_Condition']

In [54]:
ohe = OneHotEncoder(handle_unknown='ignore')
ohe.fit(X_train[features])
top3 = ohe.transform(X_train[features]).toarray()

In [56]:
lm_ovr.fit(top3, y_train)

LogisticRegression(max_iter=10000, multi_class='ovr')

In [57]:
lm_mn.fit(top3, y_train)

LogisticRegression(max_iter=10000, multi_class='multinomial')

In [58]:
top3_val = ohe.transform(X_val[features]).toarray()

In [59]:
preds_ovr = lm_ovr.predict(top3_val)
preds_mn = lm_mn.predict(top3_val)

In [60]:
print("LRovr confusion matrix: \n\n", metrics.confusion_matrix(y_val, preds_ovr,labels=['Adoption','Transfer','Other']))

LRovr confusion matrix: 

 [[4554  266   53]
 [1181 3006   54]
 [ 520  517  106]]


In [61]:
print("LRovm confusion matrix: \n\n", metrics.confusion_matrix(y_val, preds_mn,labels=['Adoption','Transfer','Other']))

LRovm confusion matrix: 

 [[4552  266   55]
 [1181 3006   54]
 [ 520  517  106]]


In [17]:
preds_proba_ovr = lm_ovr.predict_proba(top3_val)
print(preds_proba_ovr)

[[0.71441564 0.07753109 0.20805327]
 [0.71441564 0.07753109 0.20805327]
 [0.09101411 0.08748359 0.8215023 ]
 ...
 [0.00273432 0.05728219 0.93998349]
 [0.74051087 0.05994931 0.19953982]
 [0.74051087 0.05994931 0.19953982]]


In [38]:
preds_proba_mn = lm_mn.predict_proba(top3_val)
print(preds_proba_mn)

[[0.72229158 0.07689426 0.20081415]
 [0.72229158 0.07689426 0.20081415]
 [0.08833144 0.08838174 0.82328683]
 ...
 [0.00171684 0.05792258 0.94036058]
 [0.74666412 0.05950939 0.1938265 ]
 [0.74666412 0.05950939 0.1938265 ]]


In [41]:
features = ['Sex_Upon_Outcome','Intake_Type','Intake_Condition','OutcomeBreed' , 'OutcomeColor']

In [42]:
ohe = OneHotEncoder(handle_unknown='ignore')
ohe.fit(X_train[features])
all5 = ohe.transform(X_train[features]).toarray()

In [46]:
lm_ovr = LogisticRegression(multi_class='ovr',max_iter=10000)

In [47]:
lm_ovr.fit(all5, y_train)

LogisticRegression(max_iter=10000, multi_class='ovr')

In [49]:
all5_val = ohe.transform(X_val[features]).toarray()

In [50]:
preds_ovr = lm_ovr.predict(all5_val)

In [51]:
print("LRovr confusion matrix: \n\n", metrics.confusion_matrix(y_val, preds_ovr,labels=['Adoption','Transfer','Other']))

LRovr confusion matrix: 

 [[4550  268   55]
 [1181 3004   56]
 [ 520  505  118]]
